package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"

	"github.com/xaaha/address-api/graph/model"
)

// CountryCode is the resolver for the countryCode field.
func (r *queryResolver) CountryCode(ctx context.Context, country *string) ([]string, error) {
	panic(fmt.Errorf("not implemented: CountryCode - countryCode"))
}

// AddressesByCountryCode is the resolver for the addressesByCountryCode field.
func (r *queryResolver) AddressesByCountryCode(ctx context.Context, countryCode string, count *int32) ([]*model.Address, error) {
	panic(fmt.Errorf("not implemented: AddressesByCountryCode - addressesByCountryCode"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
