// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Address struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Phone       *string `json:"phone,omitempty"`
	CountryCode *string `json:"countryCode,omitempty"`
	Country     *string `json:"country,omitempty"`
}

type Query struct {
}
